//
//  SNRPromotionSortingKey.h
//  SyneriseSDK
//
//  Created by Synerise
//  Copyright (c) 2025 Synerise. All rights reserved.
//

NS_ASSUME_NONNULL_BEGIN

typedef NSString * SNRPromotionSortingKey;

FOUNDATION_EXPORT SNRPromotionSortingKey const SNR_PROMOTION_SORTING_KEY_EXPIRE_AT;
FOUNDATION_EXPORT SNRPromotionSortingKey const SNR_PROMOTION_SORTING_KEY_CREATED_AT;
FOUNDATION_EXPORT SNRPromotionSortingKey const SNR_PROMOTION_SORTING_KEY_LASTING_AT;
FOUNDATION_EXPORT SNRPromotionSortingKey const SNR_PROMOTION_SORTING_KEY_REQUIRE_REDEEMED_POINTS;
FOUNDATION_EXPORT SNRPromotionSortingKey const SNR_PROMOTION_SORTING_KEY_UPDATED_AT;
FOUNDATION_EXPORT SNRPromotionSortingKey const SNR_PROMOTION_SORTING_KEY_TYPE;
FOUNDATION_EXPORT SNRPromotionSortingKey const SNR_PROMOTION_SORTING_KEY_PRIORITY;

NS_ASSUME_NONNULL_END
