//
//  SyneriseModelStringRepresentation.swift
//  SampleAppSwift
//
// Created by Synerise
// Copyright (c) 2025 Synerise. All rights reserved.
//

import Foundation
import SyneriseSDK

class SyneriseModelStringRepresentation {
  // MARK: - Static (Internal)

  static func makePromotionsListStringRepresentation(_ model: PromotionResponse) -> String {
    var stringRepresentation = ""

    for promotion in model.items {
      let promotionStringRepresentation = makePromotionStringRepresentation(promotion)
      stringRepresentation.append("\n- - - - - - - - - - - - - - - - - - - - -\n")
      stringRepresentation.append(promotionStringRepresentation)
    }

    return stringRepresentation
  }

  static func makePromotionStringRepresentation(_ model: Promotion) -> String {
    let uuid = model.uuid
    let code = model.code
    let status = model.status.toString()
    let type = model.type.toString()

    let redeemLimitPerClient = model.redeemLimitPerClient?.stringValue ?? "-"
    let redeemQuantityPerActivation = model.redeemQuantityPerActivation?.stringValue ?? "-"
    let currentRedeemedQuantity = model.currentRedeemedQuantity?.stringValue ?? "-"
    let currentRedeemLimit = model.currentRedeemLimit?.stringValue ?? "-"
    let activationCounter = model.activationCounter?.stringValue ?? "-"
    let possibleRedeems = model.possibleRedeems?.stringValue ?? "-"
    let requireRedeemedPoints = model.requireRedeemedPoints?.stringValue ?? "-"

    let discountType = model.discountType.toString()
    let discountValue = model.discountValue
    let discountMode = model.discountMode.toString()

    let name = model.name
    let headline = model.headline ?? "-"
    let descriptionText = model.descriptionText ?? "-"

    let priority = model.priority.stringValue
    let price = model.price.stringValue
    let minBasketValue = model.minBasketValue?.stringValue ?? "-"
    let maxBasketValue = model.maxBasketValue?.stringValue ?? "-"

    var vouchers = ""
    if let voucherItems = model.vouchers {
      if voucherItems.isEmpty == false {
        var voucherStringRepresentationItems: [String] = []
        for voucherItem in voucherItems {
          let voucherStringRepresentation = """
          code: \(voucherItem.code)
          status: \(voucherItem.status.toString())
          autoGenerated: \(voucherItem.autoGenerated)
          lastingAt: \(voucherItem.lastingAt?.description ?? "-")
          redeemedAt: \(voucherItem.redeemedAt?.description ?? "-")
          aassignedAt: \(voucherItem.assignedAt.description)
          """
          voucherStringRepresentationItems.append(voucherStringRepresentation)
        }
        vouchers += """
        [
        \(voucherStringRepresentationItems.joined(separator: "\n- - -"))
        ]
        """
      } else {
        vouchers = "[]"
      }
    } else {
      vouchers = "-"
    }

    let startAt = model.startAt?.description ?? "-"

    let expireIn = model.expireAt?.description ?? "-"
    let lastingTime = model.lastingAt?.description ?? "-"

    let displayFrom = model.displayFrom?.description ?? "-"
    let displayTo = model.displayTo?.description ?? "-"

    let images: Any = model.images?.description ?? "-"
    let catalogIndexItems: Any = model.catalogIndexItems ?? "-"
    let params: Any = model.params ?? "-"

    let stringRepresentation = """
    UUID: \(uuid)
    code: \(code)
    status: \(status)
    type: \(type)

    redeemLimitPerClient: \(redeemLimitPerClient)
    redeemQuantityPerActivation: \(redeemQuantityPerActivation)
    currentRedeemedQuantity: \(currentRedeemedQuantity)
    currentRedeemLimit: \(currentRedeemLimit)
    activationCounter: \(activationCounter)
    possibleRedeems: \(possibleRedeems)
    requireRedeemedPoints: \(requireRedeemedPoints)

    discountType: \(discountType)
    discountValue: \(discountValue)
    discountMode: \(discountMode)

    name: \(name)
    headline: \(headline)
    descriptionText: \(descriptionText)

    priority: \(priority)
    price: \(price)
    minBasketValue: \(minBasketValue)
    maxBasketValue: \(maxBasketValue)

    vouchers: \(vouchers)

    startAt: \(startAt)
    expireIn: \(expireIn)
    lastingTime: \(lastingTime)
    displayFrom: \(displayFrom)
    displayTo: \(displayTo)

    images: \(images as AnyObject)
    catalogIndexItems: \(catalogIndexItems as AnyObject)
    params: \(params as AnyObject)
    """

    return stringRepresentation
  }
}
